package team1.myshop.contracts;

public enum UserRights {

	GET_USER_INFO,
	CAN_CREATE_CATEGORY,
	CAN_CREATE_ITEM,
	CAN_CREATE_COMMENT,
	CAN_DELETE_CATEGORY,
	CAN_DELETE_ITEM,
	CAN_DELETE_COMMENT,
	CAN_DELETE_USER,
	CAN_EDIT_CATEGORY,
	CAN_EDIT_ITEM,
	CAN_EDIT_COMMENT,
	CAN_EDIT_USER
	
}
